# Setup

In [ ]:
# script for standard imports
%run '/content/drive/MyDrive/Data_Science/scripts/setup.ipynb'

In [ ]:
trx_nc_prepped = \
pd.read_csv('/content/drive/MyDrive/Data_Science/data/gtd/trx_nc_prepped.csv')

trx_nc_prepped = \
pd.read_csv('/content/drive/MyDrive/Data_Science/data/gtd/trainy.csv')

# Establish Baseline scores
- after preprocessing/transformations

In [ ]:
# check types/shapes of X/y
print(f'\
      X (train) type: {type(trx_nc_prepped)}\n\
      X shape: {trx_nc_prepped.shape}\n\n\
      \
      y (train) type: {type(trainy.values)}\n\
      y shape: {trainy.values.shape}')

      X (train) type: <class 'numpy.ndarray'>
      X shape: (153171, 37)

            y (train) type: <class 'numpy.ndarray'>
      y shape: (153171,)


In [ ]:
all_clf_models = [LogisticRegression(random_state=33,n_jobs=-1),
                  DecisionTreeClassifier(random_state=33),
                  RandomForestClassifier(random_state=33,n_jobs=-1),
                  KNeighborsClassifier(n_jobs=-1),
                  LinearSVC(random_state=33),
                  SVC(random_state=33), #try svc = SVC(probability=True)
                  MultinomialNB(),
                  SGDClassifier(random_state=33,n_jobs=-1),
                  GradientBoostingClassifier(random_state=33)]

logreg,tree,forest,knn,linsvc,svc,multi_nb,sgd,gboost = \
                        all_clf_models[0],all_clf_models[1],\
                        all_clf_models[2],all_clf_models[3],\
                        all_clf_models[4],all_clf_models[5],\
                        all_clf_models[6],all_clf_models[7],\
                        all_clf_models[8]

# classification scoring metrics (loss funcs?)
clf_metrics = [accuracy_score,precision_score,recall_score,f1_score]

# for custom function `train_predict_eval`
clf_models = [logreg,tree,forest,sgd]

### **Logisitic Regression Classifier**

In [ ]:
logreg.fit(trx_nc_prepped, trainy.values)
logreg_preds = logreg.predict(trx_nc_prepped)
display(trainy[:20].values)
display(logreg_preds[:20])

#accruacy
logreg_ac_score = accuracy_score(trainy, logreg_preds)
display(logreg_ac_score)

#accuracy evaluation w/ cv on lr
logreg_cv_acc_score = cross_val_score(
                logreg,trx_nc_prepped,trainy,
                cv=5,scoring='accuracy')
display(logreg_cv_acc_score)

#precision
logreg_pr_score = precision_score(trainy, logreg_preds)
display(logreg_pr_score)

#precision evaluation w/ cv on lr
logreg_cv_prec_score = cross_val_score(
    logreg, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(logreg_cv_prec_score)

#recall
logreg_re_score = recall_score(trainy, logreg_preds)
display(logreg_re_score)

#recall evaluation w/ cv on lr
logreg_cv_rec_score = cross_val_score(
    logreg, trx_nc_prepped, trainy, cv=5, scoring='recall')
display(logreg_cv_rec_score)

#f1
logreg_f1_score_ = f1_score(trainy, logreg_preds)
display(logreg_f1_score_)

#f1 evaluation w/ cv on lr
logreg_cv_f1_score = cross_val_score(
    logreg, trx_nc_prepped, trainy, cv=5, scoring='f1')

logreg_cv_f1_score

'f1'

**103 seconds**

    array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    0.8868650070835863
    array([0.88695936, 0.8868251 , 0.88685774, 0.88679245, 0.88702096])
    0.8869970152373114
    array([0.88702041, 0.88695141, 0.88698037, 0.88694772, 0.8870241 ])
    0.9998012308960805
    array([0.99988958, 0.99981595, 0.99981595, 0.99977914, 0.99996319])

### Decision Tree

In [ ]:
tree.fit(trx_nc_prepped, trainy.values)
tree_preds = dt.predict(trx_nc_prepped)

# accruacy
tree_ac_score = accuracy_score(trainy, tree_preds)
display(tree_ac_score)
# w/ cv
tree_cv_acc_score = cross_val_score(
    tree, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(tree_cv_acc_score)

# precision
tree_pr_score = precision_score(trainy, tree_preds)
display(tree_pr_score)
# w/ cv
tree_cv_prec_score = cross_val_score(
    tree, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(tree_cv_prec_score)

# recall
tree_re_score = recall_score(trainy, tree_preds)
display(tree_re_score)
# w/ cv
tree_cv_rec_score = cross_val_score(
    tree, trx_nc_prepped, trainy, cv=5, scoring='recall')
tree_cv_rec_score

# f1
tree_cv_f1_score = cross_val_score(
    tree, trx_nc_prepped, trainy, cv=5, scoring='f1')
# w/ cv
tree_cv_f1_score

'f1'

**18 seconds**

### forest

In [ ]:
forest.fit(trx_nc_prepped, trainy.values)
forest_preds = forest.predict(trx_nc_prepped)

# accruacy
forest_ac_score = accuracy_score(trainy, forest_preds)
display(forest_ac_score)
# w/ cv
forest_cv_acc_score = cross_val_score(
    forest, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(forest_cv_acc_score)

# precision
forest_pr_score = precision_score(trainy, forest_preds)
display(forest_pr_score)
# w/ cv
forest_cv_prec_score = cross_val_score(
    forest, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(forest_cv_prec_score)

# recall
forest_re_score = recall_score(trainy, forest_preds)
display(forest_re_score)
# w/ cv
forest_cv_rec_score = cross_val_score(
    forest, trx_nc_prepped, trainy, cv=5, scoring='recall')
display(forest_cv_rec_score)

# f1
forest_cv_f1_score = cross_val_score(
    forest, trx_nc_prepped, trainy, cv=5, scoring='f1')
# w/ cv
forest_cv_f1_score

'f1'

**252 seconds** (4min)

### SGD

In [ ]:
sgd.fit(trx_nc_prepped, trainy.values)
sgd_preds = sgd.predict(trx_nc_prepped)

# accruacy
sgd_ac_score = accuracy_score(trainy, sgd_preds)
display(sgd_ac_score)
#w/ cv
sgd_cv_acc_score = cross_val_score(
    sgd, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(sgd_cv_acc_score)

# precision
sgd_pr_score = precision_score(trainy, sgd_preds)
display(sgd_pr_score)
#w/ cv
sgd_cv_prec_score = cross_val_score(
    sgd, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(sgd_cv_prec_score)

# recall
sgd_re_score = recall_score(trainy, sgd_preds)
display(sgd_re_score)
#w/ cv
sgd_cv_rec_score = cross_val_score(
    sgd, trx_nc_prepped, trainy, cv=5, scoring='recall')
display(sgd_cv_rec_score)

# f1
sgd_f1_score = f1_score(trainy, sgd_preds)
display(sgd_f1_score)
#w/ cv
sgd_cv_f1_score = cross_val_score(
    sgd, trx_nc_prepped, trainy, cv=5, scoring='f1')
sgd_cv_f1_score

'f1'

**34 seconds**

### knn

In [ ]:
knn.fit(trx_nc_prepped, trainy.values)
knn_preds = knn.predict(trx_nc_prepped)
display(trainy[:20].values)
display(knn_preds[:20])

# accruacy
knn_ac_score = accuracy_score(trainy, knn_preds)
display(knn_ac_score)
# w/ cv
knn_cv_acc_score = cross_val_score(
    knn, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(knn_cv_acc_score)

# precision
knn_pr_score = precision_score(trainy, knn_preds)
display(knn_pr_score)
# w/ cv
knn_cv_prec_score = cross_val_score(
    knn, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(knn_cv_prec_score)

# recall
knn_re_score = recall_score(trainy, knn_preds)
display(knn_re_score)
# w/ cv
knn_cv_rec_score = cross_val_score(
    knn, trx_nc_prepped, trainy, cv=5, scoring='recall')

display(knn_cv_rec_score)

# f1
knn_f1_score = f1_score(trainy, knn_preds)
display(knn_f1_score)
#w/ cv
knn_f1_score = cross_val_score(
    sgd, trx_nc_prepped, trainy, cv=5, scoring='f1')
knn_cv_f1_score

'f1'

**2362 seconds** (39min)


### linSvc

In [ ]:
linsvc.fit(trx_nc_prepped, trainy.values)
linsvc_preds = linsvc.predict(trx_nc_prepped)
display(trainy[:20].values)
display(linsvc_preds[:20])

linsvc_ac_score = accuracy_score(trainy, linsvc_preds)
display(linsvc_ac_score)

linsvc_cv_acc_score = cross_val_score(
    linsvc, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(linsvc_cv_acc_score)

linsvc_pr_score = precision_score(trainy, linsvc_preds)
display(linsvc_pr_score)

linsvc_cv_prec_score = cross_val_score(
    linsvc, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(linsvc_cv_prec_score)

linsvc_re_score = recall_score(trainy, linsvc_preds)
display(linsvc_re_score)

linsvc_cv_rec_score = cross_val_score(
    linsvc, trx_nc_prepped, trainy, cv=5, scoring='recall')
display(linsvc_cv_rec_score)

# f1
linsvc_f1_score = f1_score(trainy, linsvc_preds)
display(linsvc_f1_score)
#w/ cv
linsvc_f1_score = cross_val_score(
    linsvc, trx_nc_prepped, trainy, cv=5, scoring='f1')
linsvc_cv_f1_score

**762 seconds** (12.7min)

    array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    0.8868062492247227
    array([0.88673086, 0.88545407, 0.88675981, 0.88679245, 0.88675981])
    0.8868236185103938
    array([0.88684296, 0.88906065, 0.88681771, 0.8868214 , 0.88681771])
    0.999977914544009
    array([0.99985277, 0.99499393, 0.99992638, 0.99996319, 0.99992638])

### SVC

In [ ]:
# %timeit
# svc.fit(trx_nc_prepped, trainy.values)
# svc_preds = svc.predict(trx_nc_prepped)
# display(trainy[:20].values)
# display(svc_preds[:20])
# %timeit
# ac_score = accuracy_score(trainy, svc_preds)
# display(ac_score)
# %timeit
# cv_acc_score = cross_val_score(
#     svc, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)
# pr_score = precision_score(trainy, svc_preds)
# display(pr_score)
# cv_prec_score = cross_val_score(
#     svc, trx_nc_prepped, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
# re_score = recall_score(trainy, svc_preds)
# display(re_score)
# cv_rec_score = cross_val_score(
#     svc, trx_nc_prepped, trainy, cv=5, scoring='recall')

# cv_rec_score

"""had problems with memory 
(took super long to execute, longer than all the below)"""

'had problems with memory \n(took super long to execute, longer than all the below)'

In [ ]:
"""TRY:"""
# >>> svc = SVC(probability=True, random_state=33)

'TRY:'

### MultiNomialNB

In [ ]:
from sklearn.naive_bayes import MultinomialNB

multi_nb.fit(trx_nc_prepped, trainy.values)
multi_nb_preds = multi_nb.predict(trx_nc_prepped)

#accruacy
multi_nb_ac_score = accuracy_score(trainy, multi_nb_preds)
display(multi_nb_ac_score)
# w/ cv
multi_nb_cv_acc_score = cross_val_score(
    multi_nb, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(multi_nb_cv_acc_score)

#precision
multi_nb_pr_score = precision_score(trainy, multi_nb_preds)
display(multi_nb_pr_score)
# w/ cv
multi_nb_cv_prec_score = cross_val_score(
    multi_nb, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(multi_nb_cv_prec_score)

#recall
multi_nb_re_score = recall_score(trainy, multi_nb_preds)
display(multi_nb_re_score)
# w/ cv
multi_nb_cv_rec_score = cross_val_score(
    multi_nb, trx_nc_prepped, trainy, cv=5, scoring='recall')
display(multi_nb_cv_rec_score)

#f1
multi_nb_cv_f1_score = cross_val_score(
    multi_nb, trx_nc_prepped, trainy, cv=5, scoring='f1')
# w/ cv
multi_nb_cv_f1_score

'f1'

### GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gboost.fit(trx_nc_prepped, trainy.values)
gboost_preds = gboost.predict(trx_nc_prepped)

#accruacy
gboost_ac_score = accuracy_score(trainy, gboost_preds)
display(gboost_ac_score)
# w/ cv
gboost_cv_acc_score = cross_val_score(
    gboost, trx_nc_prepped, trainy, cv=5, scoring='accuracy')
display(gboost_cv_acc_score)

#precision
gboost_pr_score = precision_score(trainy, multi_nb_preds)
display(gboost_pr_score)
# w/ cv
gboost_cv_prec_score = cross_val_score(
    gboost, trx_nc_prepped, trainy, cv=5, scoring='precision')
display(gboost_cv_prec_score)

#recall
gboost_re_score = recall_score(trainy, gboost_preds)
display(gboost_re_score)
# w/ cv
gboost_cv_rec_score = cross_val_score(
    gboost, trx_nc_prepped, trainy, cv=5, scoring='recall')
display(gboost_cv_rec_score)

#f1
gboost_cv_f1_score = cross_val_score(
    gboost, trx_nc_prepped, trainy, cv=5, scoring='f1')
# w/ cv
gboost_cv_f1_score

'f1'