Previous notebook, _"preprocessing.ipynb"_ completed steps:
1. Initial data adjustments
2. Preprocessing

# setup

In [ ]:
# script for standard imports
%run '/content/drive/MyDrive/Data_Science/scripts/setup.ipynb'

# read-in preprocessed trainx set, "trx_preproc"
trx_preproc = \
pd.read_csv('/content/drive/MyDrive/Data_Science/data/gtd/trx_preproc.csv')

trainy = \
pd.read_csv('/content/drive/MyDrive/Data_Science/data/gtd/trainy.csv')

# Establish Baseline scores 
_(on numeric/categoric only)_

In [ ]:
# check types/shapes of X/y
print(f'\
      X (train) type: {type(trx_preproc)}\n\
      X shape: {trx_preproc.shape}\n\n\
      \
      y (train) type: {type(trainy.values)}\n\
      y shape: {trainy.values.shape}')

      X (train) type: <class 'numpy.ndarray'>
      X shape: (153171, 37)

            y (train) type: <class 'numpy.ndarray'>
      y shape: (153171,)


In [ ]:
all_clf_models = [LogisticRegression(random_state=33,n_jobs=-1),
                  DecisionTreeClassifier(random_state=33),
                  RandomForestClassifier(random_state=33,n_jobs=-1),
                  KNeighborsClassifier(n_jobs=-1),
                  LinearSVC(random_state=33),
                  SVC(random_state=33), #try svc = SVC(probability=True)
                  MultinomialNB(),
                  SGDClassifier(random_state=33,n_jobs=-1),
                  GradientBoostingClassifier(random_state=33)]

lr,tree,forest,knn,linsvc,svc,multi_nb,sgd,gboost = \
                        all_clf_models[0],all_clf_models[1],\
                        all_clf_models[2],all_clf_models[3],\
                        all_clf_models[4],all_clf_models[5],\
                        all_clf_models[6],all_clf_models[7],\
                        all_clf_models[8]

# classification scoring metrics (loss funcs?)
clf_metrics = [accuracy_score,precision_score,recall_score,f1_score]

# for custom function `train_predict_eval`
clf_models = [lr,tree,forest,sgd]

### **Logisitic Regression Classifier**

In [ ]:
'''# # Linear Regresion: y = mx+b'''
# lr.fit(trx_preproc, trainy.values)
# lr_preds = lr.predict(trx_preproc)

'''accruacy'''
# ac_score = accuracy_score(trainy, lr_preds)
# display(ac_score)

# #accuracy evaluation w/ cv on lr
# cv_acc_score = cross_val_score(
#                 lr,trx_preproc,trainy,
#                 cv=5,scoring='accuracy')
# display(cv_acc_score)
'''precision'''
# pr_score = precision_score(trainy, lr_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     lr, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
'''recall'''
# re_score = recall_score(trainy, lr_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     lr, trx_preproc, trainy, cv=5, scoring='recall')
# display(cv_rec_score)
'''f1'''
# f1_score_ = f1_score(trainy, lr_preds)
# display(f1_score_)

# cv_f1_score = cross_val_score(
#     lr, trx_preproc, trainy, cv=5, scoring='f1')

# cv_f1_score

'f1'

**103 seconds**

    array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    0.8868650070835863
    array([0.88695936, 0.8868251 , 0.88685774, 0.88679245, 0.88702096])
    0.8869970152373114
    array([0.88702041, 0.88695141, 0.88698037, 0.88694772, 0.8870241 ])
    0.9998012308960805
    array([0.99988958, 0.99981595, 0.99981595, 0.99977914, 0.99996319])

### Decision Tree

In [ ]:
# tree.fit(trx_preproc, trainy.values)
# tree_preds = tree.predict(trx_preproc)
'''accruacy'''
# ac_score = accuracy_score(trainy, tree_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     tree, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)
'''precision'''
# pr_score = precision_score(trainy, tree_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     tree, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
'''recall'''
# re_score = recall_score(trainy, tree_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     tree, trx_preproc, trainy, cv=5, scoring='recall')
# cv_rec_score
'''f1'''
# tree_cv_f1_score = cross_val_score(
#     tree, trx_preproc, trainy, cv=5, scoring='f1')

# tree_cv_f1_score

'f1'

**18 seconds**

### forest

In [ ]:
# forest.fit(trx_preproc, trainy.values)
# forest_preds = forest.predict(trx_preproc)
'''accruacy'''
# ac_score = accuracy_score(trainy, forest_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     forest, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)
'''precision'''
# pr_score = precision_score(trainy, forest_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     forest, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
'''recall'''
# re_score = recall_score(trainy, forest_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     forest, trx_preproc, trainy, cv=5, scoring='recall')
# cv_rec_score
'''f1'''
# forest_cv_f1_score = cross_val_score(
#     forest, trx_preproc, trainy, cv=5, scoring='f1')

# forest_cv_f1_score

'f1'

**252 seconds** (4min)

### SGD

In [ ]:
# sgd.fit(trx_preproc, trainy.values)
# sgd_preds = sgd.predict(trx_preproc)
'''accruacy'''
# ac_score = accuracy_score(trainy, sgd_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     sgd, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)
'''precision'''
# pr_score = precision_score(trainy, sgd_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     sgd, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
'''recall'''
# re_score = recall_score(trainy, sgd_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     sgd, trx_preproc, trainy, cv=5, scoring='recall')
# cv_rec_score
'''f1'''
# sgd_cv_f1_score = cross_val_score(
#     sgd, trx_preproc, trainy, cv=5, scoring='f1')

# sgd_cv_f1_score

'f1'

**34 seconds**

### knn

In [ ]:
# knn.fit(trx_preproc, trainy.values)
# knn_preds = knn.predict(trx_preproc)
# display(trainy[:20].values)
# display(knn_preds[:20])
'''accruacy'''
'''precision'''
'''recall'''
'''f1'''
# ac_score = accuracy_score(trainy, knn_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     knn, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)
'''accruacy'''
'''precision'''
'''recall'''
'''f1'''
# pr_score = precision_score(trainy, knn_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     knn, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
'''accruacy'''
'''precision'''
'''recall'''
'''f1'''
# re_score = recall_score(trainy, knn_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     knn, trx_preproc, trainy, cv=5, scoring='recall')

# cv_rec_score

'f1'

**2362 seconds** (39min)


### linSvc

In [ ]:
# linsvc.fit(trx_preproc, trainy.values)
# linsvc_preds = linsvc.predict(trx_preproc)
# display(trainy[:20].values)
# display(linsvc_preds[:20])

# ac_score = accuracy_score(trainy, linsvc_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     linsvc, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)

# pr_score = precision_score(trainy, linsvc_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     linsvc, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)

# re_score = recall_score(trainy, linsvc_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     linsvc, trx_preproc, trainy, cv=5, scoring='recall')

# cv_rec_score

**762 seconds** (12.7min)

    array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
    0.8868062492247227
    array([0.88673086, 0.88545407, 0.88675981, 0.88679245, 0.88675981])
    0.8868236185103938
    array([0.88684296, 0.88906065, 0.88681771, 0.8868214 , 0.88681771])
    0.999977914544009
    array([0.99985277, 0.99499393, 0.99992638, 0.99996319, 0.99992638])

### SVC

In [ ]:
# %timeit
# svc.fit(trx_preproc, trainy.values)
# svc_preds = svc.predict(trx_preproc)
# display(trainy[:20].values)
# display(svc_preds[:20])
# %timeit
# ac_score = accuracy_score(trainy, svc_preds)
# display(ac_score)
# %timeit
# cv_acc_score = cross_val_score(
#     svc, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)
# pr_score = precision_score(trainy, svc_preds)
# display(pr_score)
# cv_prec_score = cross_val_score(
#     svc, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)
# re_score = recall_score(trainy, svc_preds)
# display(re_score)
# cv_rec_score = cross_val_score(
#     svc, trx_preproc, trainy, cv=5, scoring='recall')

# cv_rec_score

"""had problems with memory 
(took super long to execute, longer than all the below)"""

'had problems with memory \n(took super long to execute, longer than all the below)'

In [ ]:
"""TRY:"""
# >>> svc = SVC(probability=True, random_state=33)

'TRY:'

### MultiNomialNB

In [ ]:
# from sklearn.naive_bayes import MultinomialNB

# multi_nb.fit(trx_preproc, trainy.values)
# multi_nb_preds = multi_nb.predict(trx_preproc)

'''accruacy'''
# ac_score = accuracy_score(trainy, multi_nb_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     multi_nb, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)

'''precision'''
# pr_score = precision_score(trainy, multi_nb_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     multi_nb, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)

'''recall'''
# re_score = recall_score(trainy, multi_nb_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     multi_nb, trx_preproc, trainy, cv=5, scoring='recall')
# cv_rec_score

'''f1'''
# multi_nb_cv_f1_score = cross_val_score(
#     multi_nb, trx_preproc, trainy, cv=5, scoring='f1')

# multi_nb_cv_f1_score

'f1'

### GradientBoostingClassifier

In [ ]:
# from sklearn.ensemble import GradientBoostingClassifier

# gboost.fit(trx_preproc, trainy.values)
# gboost_preds = gboost.predict(trx_preproc)

'''accruacy'''
# ac_score = accuracy_score(trainy, gboost_preds)
# display(ac_score)

# cv_acc_score = cross_val_score(
#     gboost, trx_preproc, trainy, cv=5, scoring='accuracy')
# display(cv_acc_score)

'''precision'''
# pr_score = precision_score(trainy, multi_nb_preds)
# display(pr_score)

# cv_prec_score = cross_val_score(
#     gboost, trx_preproc, trainy, cv=5, scoring='precision')
# display(cv_prec_score)

'''recall'''
# re_score = recall_score(trainy, gboost_preds)
# display(re_score)

# cv_rec_score = cross_val_score(
#     gboost, trx_preproc, trainy, cv=5, scoring='recall')
# cv_rec_score

'''f1'''
# multi_nb_cv_f1_score = cross_val_score(
#     gboost, trx_preproc, trainy, cv=5, scoring='f1')

# gboost_cv_f1_score

'f1'

# Next Steps

data preparation (on _"trx_preproc"_) via transformations for machine learning (see, _"data transformations.ipynb"_). 